---
title: "Books"
author:

<!--  output: html_document -->
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This course has no required text, but the following books might be useful. In each of the sections below the references are listed in order from basic to more advanced.

***

## General biostatistics books
Whitlock, M. and D. Schluter. 2020. 3<sup>rd</sup> edition. The analysis of biological data. Greenwood Village, Colo., Roberts and Co. Publishers.

<small> <i>A readable introduction to analyzing data in biology. A good place to refresh your skills. Biol 501 assumes that you have already taken an undergraduate course in statistics and are familiar with basic principles covered in Chapters 1 through 17. Some of the material in the later chapters will be used in this course.</i></small>

<small> R commands to analyze the data for all examples presented in this 3<sup>rd</sup> edition are <a href="https://whitlockschluter3e.zoology.ubc.ca/RExamples/index.html"><i>here</i></a>.</small>

Quinn, G. P. and M. J. Keough. 2002. Experimental design and data analysis for biologists. Cambridge, UK; New York, Cambridge University Press.

<small><i>An excellent second course in statistics and biological data analysis. Emphasis of examples is ecology, especially marine intertidal ecology. Full of practical information on the best approaches to use in particular circumstances and the reasons why</i>.
</small>

<!--
Grafen, A. and R. Hails. 2002. Modern statistics for the life sciences. Oxford; New York, Oxford University Press.
<small style="font-style: italic;">An introduction to the general linear model approach to analyzing data. Emphasis is on concepts and intuition rather than mathematics. Heavy on hypothesis testing and light on estimation and confidence intervals.</small>
-->

***

## R books
Borcard, D., F. Gillet, and P. Legendre. 2011. Numerical ecology with R. Springer.

<small style="font-style: italic;">Based on the standard reference for ordination and multivariate methods in ecology. </small>
<a href="http://link.springer.com/book/10.1007/978-1-4419-7976-6">UBC Online</a>.

Crawley, M. J. 2012, The R book. 2<sup>nd</sup> edition. Chichester, England; Hoboken, N.J.,Wiley.

<small style="font-style: italic;">A helpful reference for methods in R,including linear mixed modeling.Explanations not always straightforward. His approach to model simplification is outdated. We'll be discussing alternative model selection approaches in class. </small>

Dalgaard, P. 2008, Introductory statistics with R. 2nd. ed. New York,Springer.

<small style="font-style: italic;">A clear introduction to the basics of R and how to carry out the standard methods for analyzing data. Better for starters than Crawley's but less comprehensive. </small>
<a href="http://www.springerlink.com/content/m17578/?p=7d2e08290b9040d2aba7922801f46d9a&pi=0">UBC Online</a>.

Galecki, Andrzej T. 2013. Linear mixed-effects models using R: a step-by-step approach. Springer New York

<small><span style="font-style: italic;">Takes you through linear models and gls as well as linear mixed models.</span></small>
<a href="https://link.springer.com/book/10.1007%2F978-1-4614-3900-4">UBC Online</a>.

Paradis, E. 2006. Analysis of phylogenetics and evolution with R. New York, Springer.

<small><span style="font-style: italic;">Explains how to carry out phylogenetic comparative analysis using the ape package.</span></small>
<a href="http://www.springerlink.com/content/x20480/?p=71b9a536801a44cbb1e77ffdf5dcd1e9&pi=1">UBC online</a>.

Pinheiro, J. C. and D. M. Bates. 2000. Mixed-effects models in S and S-PLUS. New York, Springer.

<small style="font-style: italic;">The standard reference for linear mixed effects modeling using R. Aimed at an advanced level. At least two of the chapters are essential reading if you use the <code>nlme</code> library in R to analyze your data. </small>
<a href="http://www.springerlink.com/content/n00145/">UBC online</a>

Stevens, M. H. H. 2009. A primer of ecology with R. New York,Springer.

<small style="font-style: italic;">Using R to analyze models and data in population and community ecology.</small>
<a href="http://www.springerlink.com/content/l48073/?p=46d1578c93c54d4b9384b69f2a6d193b&pi=16">UBC Online</a>.

Sarkar, D. 2008. Lattice: Multivariate data visualization with R. New York, Springer.

<small style="font-style: italic;">The creator of the lattice package explains all.</small>
<a href="http://www.springerlink.com/content/kr8v78/?p=71b9a536801a44cbb1e77ffdf5dcd1e9&pi=7"> UBC online</a>.

Venables, W. N. and B. D. Ripley. 2002. Modern applied statistics with S-PLUS. 4th. New York, Springer.

<small style="font-style: italic;">The standard reference for statistical analysis of data using R and S. Covers most of the methods you will every need.</small>
<a href="http://www.springer.com.ezproxy.library.ubc.ca/us/book/9780387954578"> UBC online</a>.

Wickam, H. 2016. ggplot2: Elegant graphics for data analysis. 2<sup>nd</sup> edition.

<small style="font-style: italic;">How to create graphs using the increasingly popular ggplot2.</small>
<a href="http://link.springer.com.ezproxy.library.ubc.ca/book/10.1007/978-3-319-24277-4"> UBC online</a>.

Zuur, A. F., E. N. Ieno and E. Meesters. 2009. A beginner's guide to R. New York, Springer.

<small style="font-style: italic;">A readable, detailed introduction to data manipulation and plotting in R. Doesn't get much farther with data analysis than tables and graphs.</small>
<a href="http://www.springerlink.com/content/w26370/?p=7521c40e70af47478a9d52fc85deaacc&pi=17">UBC Online</a>.

Zuur, A. F., E. N. Ieno, N. J. Walker, A. A. Saveliev and G. M.Smith. 2009. Mixed effects models and extensions in ecology with R. New York, Springer.

<small style="font-style: italic;">A useful guide to advanced methods of data analysis in ecology as well as to carrying them out in R. Topics including nonlinear regression, additive modeling, mixed-effects models, nonindependent data, generalized least squares and generalized additive models.</small>
<a href="http://www.springerlink.com/content/t41683/?p=0c07e268e5144d079de2e122020ef82f&pi=1">UBC Online</a>.

***

## More specialized references
Bolker, B. M. 2008. Ecological models and data in R. Princeton, NJ,Princeton University Press.

<small style="font-style: italic;">A good complement to Hilborn and Mangel, with the added practical information on how to implement the general approach using R. Has a good overview chapter on likelihood.</small>

Burnham, K. P. and D. R. Anderson. 2002. Model selection and multimodel inference: a practical information-theoretic approach. 2nd.New York, Springer.

<small style="font-style: italic;">The authoritative treatise on modern approaches to model selection.</small>
<a href="http://link.springer.com/book/10.1007%2Fb97636">UBC Online</a>

Efron, B. and R. Tibshirani. 1998. An introduction to the bootstrap. Boca Raton, FL, Chapman & Hall/CRC Press.

<small style="font-style: italic;">An accessible introduction, at least the first few chapters.</small>

Felsenstein, J. 2004. Inferring phylogenies. Sunderland,Mass, Sinauer.

<small><span style="font-style: italic;">The master's voice. Chapter 25 is a clear and compact summary of comparative methods.</span></small>

Gotelli, N. J. and A. M. Ellison. 2004. A primer of ecological statistics. Sunderland, Mass., Sinauer Associates Publishers.

<small style="font-style: italic;">A clear overview of basic principles and methods in analyzing ecological data. Not particularly rich with data or examples. The overview of multivariate methods is excellent.</small>

Hilborn, R. and M. Mangel. 1997. The ecological detective: confronting models with data. Princeton, NJ, Princeton University Press.

<small style="font-style: italic;">A great overview of howto fit models to data using a likelihood and model selection approach.</small>
