---
title: "Handouts"
author:

<!--  output: html_document -->
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This page lists and links to the required readings for the term. Readings might change as the term progresses. Refresh the page on your browser to see the latest version.

Dates indicate when the paper is to be <strong>discussed</strong>, so read well beforehand.

<br>

## Discussion dates and papers
### September 15
<a href="readings/wainer%201984%20amer%20stat%20-%20how%20to%20display%20data%20badly.pdf">Wainer: How to display data badly</a>

### September 22
<a href="readings/hurlbert 1984 ecol monogr - pseudoreplication.pdf">Hurlbert: Pseudoreplication and the design of experiments</a>

### September 29
<a href="readings/colegrave & ruxton 2003 behav ecol - use confidence intervals not post-hoc power when Ho not rejected.pdf">Colegrave & Ruxton: Confidence intervals</a>

Optional additional reading: <a href="readings/hoenig & heisey 2001 am stat - fallacy of power calculations for data analysis.pdf" rel="">Hoenig & Heisey 2001</a>)

### October 6
<a href="readings/kelly & price 2005 am nat - regression toward the mean.pdf">Kelly and Price: Correcting for regression to the mean</a>

Optional additional reading:&nbsp;<a href="readings/forstmeier 2011 anat rec - brain size fallacy.pdf" rel="">Forstmeier 2011</a> and&nbsp;<a href="https://www.zoology.ubc.ca/~schluter/reprints/schluter%201992%20nature%20-%20brain%20size%20differences.pdf" rel="">Schluter 1992</a> on a brain size fallacy.

### October 13
<a href="readings/murtaugh 2007 ecology - simplicity and complexity in data analysis.pdf">Murtaugh: Simplicity in data analysis</a>

### October 20
<a href="readings/verhoeven et al 2005 oikos - controlling the false discovery rate.pdf">Verhoeven et al: Controlling false discovery rate</a>

### October 27
<a href="readings/whittingham et al 2006 jae - why not to use stepwise modeling.pdf">Whittingham et al: Why do we still use stepwise regression?</a>

Optional additional reading:&nbsp;<a href="readings/mundry et al 2009 am nat - more on why not to use stepwise model fitting.pdf">Mundry & Nunn: more on stepwise regression</a>

### November 3
<a href="readings/cohen 1994 am psych - the earth is round.pdf">Cohen: The earth is round (p < 0.05)</a>

### November 10
<a href="readings/dochtermann & jenkins 2011 bes - developing multiple hypotheses in behavioural ecology.pdf">Dochtermann & Jenkins: Working with multiple hypotheses</a>

Optional additional reading:&nbsp;<a href="readings/bettini et al 2017 rsos - why are we not testing multiple hypotheses.pdf">Betini et al: why are we not testing multiple hypotheses</a>

### November 17
<a href="readings/palmer 1999 metaanalysis of fluctuating asymmetry and sexual selection.pdf">Palmer: Publication bias in fluctuating asymmetry</a>

### November 24
<a href="readings/longmuir et al 2007 ecology - diversity gradients in plankton.pdf">Longmuir et al: Multivariate biodiversity gradients</a> <!-- <a href="readings/richman & price 1992 nature - evolution leaf warblers.pdf" rel="">Richman and Price: Evolution of ecological differences in warblers</a>. 
Optional additional reading: <a href="readings/price 1991 jae - ecology of leaf warblers.pdf">Price 1991</a> which shows the process of PCA more clearly. -->

### December 1
<a href="readings/jetz et al 2014 curr biol - conservation and phylogenetic distinctness.pdf">Jetz et al: Phylogenetic distinctness and conservation</a>

<!--
### December 6
tba 
<a href="readings/longmuir et al 2007 ecology - diversity gradients in plankton.pdf">Longmuir et al: Diversity gradients in lake plankton</a>
-->
