---
title: "Lectures 2020"
author:

<!--  output: html_document -->
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
---

<!-- 
setwd("/Users/schluter/zoologyCloud/Courses/bio 501 - stats/www-biol501")
rmarkdown::render("lectures.Rmd", "html_document")
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This page is under continuous revision, with new information added as the term proceeds.

Lectures (Tuesdays 1-3 pm) and workshops (Thursdays 1-3 pm) are held on Zoom (link will be emailed).
</b>.

Below is an approximate list of lecture topics and contents. Links to the lecture slides will be added before each lecture. Click the refresh button on your browser to make sure you are seeing the latest version of this page.

***

## Introduction
<a href="lecturepdf/01.introduction.pdf">Lecture slides</a><!--
<br><a href="https://youtu.be/UFABvRzxFt0">Lecture video</a> -->
<br>About the course
<br>Course objectives
<br>About the instructor
<br>Why we use R
<br>Organizing data for use in R

<br>

## Graphics
<a href="lecturepdf/02.Graphics.pdf">Lecture slides</a><!--
<br><a href="https://youtu.be/b9oRMiy-CNk">Lecture video</a> -->
<br>The purpose of graphs
<br>Principles of effective display
<br>Types of graphs to achieve these principles
<br>How some graphs fail, and what can be done
<br>What about tables?

<br>

## Design of experiments<!--
<a href="lecturepdf/03.Design.pdf">Lecture slides</a>
<br><a href="https://youtu.be/27b-qZKkraU">Lecture video</a> -->
<br>Plan your sample size
<br>Experiments vs observational studies
<br>Why do experiments
<br>Clinical trials: experiments on people
<br>Design experiments to minimize bias and effects of sampling error
<br>Analysis follows design
<br>What if you can’t do experiments

<br>

## Linear models<!--
<a href="lecturepdf/04.Linear models.pdf">Lecture slides</a>
<br><a href="https://youtu.be/WYKBgzDjpbs">Lecture video</a> -->
<br>What is a linear model
<br>Several examples
<br>Estimating parameters vs testing hypotheses
<br>Model comparison: "full" vs "reduced" models
<br>Sequential vs marginal testing of terms
<br>The lure of model simplification
<br>Perils of correcting for covariates
<br>Assumptions of linear models
<br>Related methods in R

<br>

## Mixed effects models<!--
<a href="lecturepdf/05.Models with random effects.pdf">Lecture slides</a>
<br><a href="https://youtu.be/nhjNQ2RFZD8">Lecture video</a> -->
<br>Random vs fixed effects
<br>Two-factor ANOVA example
<br>Why the calculations are different with random effects
<br>Unbalanced designs with random effects
<br>Examples of experiments with random effects
<br>Linear mixed-effects models
<br>Example: Estimating repeatability of a measurement
<br>Assumptions of linear mixed-effects models
<br>An example violating the assumptions, with solutions

<br>

## Likelihood<!--
<a href="lecturepdf/06.Likelihood.pdf">Lecture slides</a>
<br><a href="https://www.youtube.com/watch?v=0boae1DxjZ8&feature=youtu.be">Lecture video</a> -->
<br>Probability and likelihood
<br>Maximum likelihood estimation
<br>Example: estimate a proportion
<br>Likelihood works backward from probability
<br>Likelihood-based confidence intervals
<br>Example: estimate speciation and extinction rates
<br>Log-likelihood ratio test
<br>Example: test a proportion

<br>

## Generalized linear models<!--
<a href="lecturepdf/07.Glm.pdf">Lecture slides</a>
<br><a href="https://youtu.be/Ds3fajlfZJs">Lecture video</a> (Because of a technical glitch, this is the 2017 lecture) -->
<br>What is a generalized linear model
<br>Linear predictors and link functions
<br>Example: estimate a proportion
<br>Analysis of deviance table
<br>Example: fit dose-response data using logistic regression
<br>Example: fit count data using a log-linear model
<br>Example: model contingency tables
<br>Advantages and assumptions of glm
<br>Quasi-likelihood modeling when there is excessive variance

<br>

## Model selection<!--
<a href="lecturepdf/08.Modelselection.pdf">Lecture slides</a>
<br><a href="https://youtu.be/qYSWp3XpDRw">Lecture video</a> -->
<br>Example: polynomial regression
<br>The problem of model selection
<br>Choose among models using an explicit criterion
<br>Goals of model selection
<br>Criterion: AIC
<br>Example: predicting ant species richness
<br>Search strategies: dredge(), stepAIC()
<br>Several models may fit about equally well
<br>The science part: formulate a set of candidate models
<br>Example: adaptive evolution in the fossil record

<br>

## Bayesian data analysis<!--
<a href="lecturepdf/09.Bayes.pdf">Lecture slides</a>
<br><a href="https://youtu.be/0FAeusbGdbU">Lecture video</a> -->
<br>What is probability
<br>Another definition of probability
<br>Bayes Theorem
<br>Prior probability and posterior probability
<br>How Bayesian inference is different from what we usually do
<br>Example: one species or two
<br>Example: estimate a proportion
<br>Credible intervals
<br>Bayes factor
<br>Bayesian model selection

<br>

## Bootstrap and resampling<!--
<a href="lecturepdf/10.Bootstrap.pdf">Lecture slides</a>
<br><a href="https://youtu.be/83HvfuBNsGE">Lecture video</a> -->
<br>Estimation and hypothesis testing
<br>Permutation test
<br>Estimation
<br>The sampling distribution
<br>The bootstrap standard error
<br>The bootstrap confidence interval
<br>Comparing two groups

<br>

## Meta-analysis<!--
<a href="lecturepdf/11.Meta-analysis.pdf">Lecture slides</a>
<br><a href="https://youtu.be/SrPtJ8cTowY">Lecture video</a> -->
<br>Meta-analysis compared with traditional review article
<br>Quantitative summaries compared with vote-counting
<br>How to carry out a meta-analysis
<br>Effect size
<br>Fixed and random effects
<br>Publication bias
<br>Make your results accessible to meta-analysis
<br>Consider a mata-analysis for your first thesis chapter
<br>Best practices

<br>

## Multivariate statistics<!--
<a href="lecturepdf/12.Multivariate.pdf">Lecture slides</a>
<br><a href="https://youtu.be/I66NDLrJhWA">Lecture video</a> -->
<br>Why do a multivariate analysis
<br>Ordination, classification, model fitting
<br>Principal component analysis
<br>Discriminant analysis, quickly
<br>Species presence/absence data
<br>Distance data

<br>

## Species as data points<!--
<a href="lecturepdf/13.Phylogenetic.pdf">Lecture slides</a>
<br><a href="https://youtu.be/ASZy3PUcALg">Lecture video</a> -->
<br>Example: the problem with species data
<br>Phylogenetic signal in ecological traits
<br>Why phylogeny matters in comparative study
<br>Phylogenetically independent contrasts
<br>A linear model (general least squares) approach
<br>A method for discrete data (and issues)
<br>Use R!

<br>

*** 

## 2019 lecture notes {#lectures2019}

These are notes from the September 2019 semester.

<a href="lecturepdf/2019/01.introduction.pdf">Introduction</a>

<a href="lecturepdf/2019/02.Graphics.pdf">Graphics</a>

<a href="lecturepdf/2019/03.Design.pdf">Design of experiments</a>

<a href="lecturepdf/2019/04.Linear models.pdf">Linear models</a> 

<a href="lecturepdf/2019/05.Models with random effects.pdf">Mixed effects models</a>

<a href="lecturepdf/2019/06.Likelihood.pdf">Likelihood</a> 

<a href="lecturepdf/2019/07.Glm.pdf">Generalized linear models</a>

<a href="lecturepdf/2019/08.Modelselection.pdf">Model selection</a> 

<a href="lecturepdf/2019/09.Bayes.pdf">Bayesian data analysis</a>

<a href="lecturepdf/2019/10.Bootstrap.pdf">Bootstrap and resampling</a>
 
<a href="lecturepdf/2019/11.Meta-analysis.pdf">Meta-analysis</a>

<a href="lecturepdf/2019/12.Multivariate.pdf">Multivariate statistics</a>

<a href="lecturepdf/2019/13.Phylogenetic.pdf">Species as data points</a> 

<br>

***

## 2019 videos of lectures {#videos2019}
<a href="https://youtu.be/UFABvRzxFt0">Introduction</a>

<a href="https://youtu.be/b9oRMiy-CNk">Graphics</a>

<a href="https://youtu.be/27b-qZKkraU">Design of experiments</a>

<a href="https://youtu.be/WYKBgzDjpbs">Linear Models</a>

<a href="https://youtu.be/nhjNQ2RFZD8">Mixed effects models</a>

<a href="https://www.youtube.com/watch?v=0boae1DxjZ8&feature=youtu.be">Likelihood</a>

<a href="https://youtu.be/Ds3fajlfZJs">Generalized linear models</a> (Because of a technical glitch, this is the 2017 lecture)

<a href="https://youtu.be/qYSWp3XpDRw">Model selection</a>

<a href="https://youtu.be/0FAeusbGdbU">Bayesian data analysis</a>

<a href="https://youtu.be/83HvfuBNsGE">Bootstrap and resampling</a>

<a href="https://youtu.be/SrPtJ8cTowY">Meta-analysis</a>

<a href="https://youtu.be/I66NDLrJhWA">Multivariate statistics</a>

<a href="https://youtu.be/ASZy3PUcALg">Species as data points</a>
